### ISSUE TITLE
fails to compile on Ubuntu 16.04 kernel 4.4.0 ?

### ISSUE THREAD

**Issue by gorogm** [xdever/cifs_old#1]
On a freshly installed Ubuntu 16.04 I couldn't compile, it is because my kernel version?
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
linux-headers-4.4.0-141-generic is already the newest version (4.4.0-141.167).
linux-headers-4.4.0-141-generic set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
make -C /lib/modules/4.4.0-141-generic/build/ M=/opt/cifs_old clean
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-141-generic'
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-141-generic'
make -C /lib/modules/4.4.0-141-generic/build/ M=/opt/cifs_old modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-141-generic'
  CC [M]  /opt/cifs_old/cifsfs.o
In file included from /opt/cifs_old/cifsfs.c:43:0:
/opt/cifs_old/cifsfs.h:131:11: warning: ‘struct delayed_call’ declared inside parameter list
    struct delayed_call *);
           ^
/opt/cifs_old/cifsfs.h:131:11: warning: its scope is only this definition or declaration, which is probably not what you want
/opt/cifs_old/cifsfs.c: In function ‘cifs_read_super’:
/opt/cifs_old/cifsfs.c:143:7: error: implicit declaration of function ‘super_setup_bdi’ [-Werror=implicit-function-declaration]
  rc = super_setup_bdi(sb);
       ^
/opt/cifs_old/cifsfs.c: In function ‘cifs_get_root’:
/opt/cifs_old/cifsfs.c:660:11: error: implicit declaration of function ‘lookup_one_len_unlocked’ [-Werror=implicit-function-declaration]
   child = lookup_one_len_unlocked(p, dentry, s - p);
           ^
/opt/cifs_old/cifsfs.c:660:9: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   child = lookup_one_len_unlocked(p, dentry, s - p);
         ^
/opt/cifs_old/cifsfs.c: At top level:
/opt/cifs_old/cifsfs.c:903:13: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .getattr = cifs_getattr,
             ^
/opt/cifs_old/cifsfs.c:903:13: note: (near initialization for ‘cifs_dir_inode_ops.getattr’)
/opt/cifs_old/cifsfs.c:908:12: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .rename = cifs_rename2,
            ^
/opt/cifs_old/cifsfs.c:908:12: note: (near initialization for ‘cifs_dir_inode_ops.rename’)
/opt/cifs_old/cifsfs.c:918:13: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .getattr = cifs_getattr,
             ^
/opt/cifs_old/cifsfs.c:918:13: note: (near initialization for ‘cifs_file_inode_ops.getattr’)
/opt/cifs_old/cifsfs.c:924:2: error: unknown field ‘get_link’ specified in initializer
  .get_link = cifs_get_link,
  ^
/opt/cifs_old/cifsfs.c:924:14: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .get_link = cifs_get_link,
              ^
/opt/cifs_old/cifsfs.c:924:14: note: (near initialization for ‘cifs_symlink_inode_ops.lookup’)
/opt/cifs_old/cifsfs.c:1074:2: error: unknown field ‘copy_file_range’ specified in initializer
  .copy_file_range = cifs_copy_file_range,
  ^
/opt/cifs_old/cifsfs.c:1074:21: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .copy_file_range = cifs_copy_file_range,
                     ^
/opt/cifs_old/cifsfs.c:1074:21: note: (near initialization for ‘cifs_file_ops.compat_ioctl’)
/opt/cifs_old/cifsfs.c:1075:2: error: unknown field ‘clone_file_range’ specified in initializer
  .clone_file_range = cifs_clone_file_range,
  ^
/opt/cifs_old/cifsfs.c:1075:22: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .clone_file_range = cifs_clone_file_range,
                      ^
/opt/cifs_old/cifsfs.c:1075:22: note: (near initialization for ‘cifs_file_ops.mmap’)
/opt/cifs_old/cifsfs.c:1092:2: error: unknown field ‘copy_file_range’ specified in initializer
  .copy_file_range = cifs_copy_file_range,
  ^
/opt/cifs_old/cifsfs.c:1092:21: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .copy_file_range = cifs_copy_file_range,
                     ^
/opt/cifs_old/cifsfs.c:1092:21: note: (near initialization for ‘cifs_file_strict_ops.compat_ioctl’)
/opt/cifs_old/cifsfs.c:1093:2: error: unknown field ‘clone_file_range’ specified in initializer
  .clone_file_range = cifs_clone_file_range,
  ^
/opt/cifs_old/cifsfs.c:1093:22: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .clone_file_range = cifs_clone_file_range,
                      ^
/opt/cifs_old/cifsfs.c:1093:22: note: (near initialization for ‘cifs_file_strict_ops.mmap’)
/opt/cifs_old/cifsfs.c:1110:2: error: unknown field ‘copy_file_range’ specified in initializer
  .copy_file_range = cifs_copy_file_range,
  ^
/opt/cifs_old/cifsfs.c:1110:21: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .copy_file_range = cifs_copy_file_range,
                     ^
/opt/cifs_old/cifsfs.c:1110:21: note: (near initialization for ‘cifs_file_direct_ops.compat_ioctl’)
/opt/cifs_old/cifsfs.c:1111:2: error: unknown field ‘clone_file_range’ specified in initializer
  .clone_file_range = cifs_clone_file_range,
  ^
/opt/cifs_old/cifsfs.c:1111:22: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .clone_file_range = cifs_clone_file_range,
                      ^
/opt/cifs_old/cifsfs.c:1111:22: note: (near initialization for ‘cifs_file_direct_ops.mmap’)
/opt/cifs_old/cifsfs.c:1128:2: error: unknown field ‘copy_file_range’ specified in initializer
  .copy_file_range = cifs_copy_file_range,
  ^
/opt/cifs_old/cifsfs.c:1128:21: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .copy_file_range = cifs_copy_file_range,
                     ^
/opt/cifs_old/cifsfs.c:1128:21: note: (near initialization for ‘cifs_file_nobrl_ops.compat_ioctl’)
/opt/cifs_old/cifsfs.c:1129:2: error: unknown field ‘clone_file_range’ specified in initializer
  .clone_file_range = cifs_clone_file_range,
  ^
/opt/cifs_old/cifsfs.c:1129:22: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .clone_file_range = cifs_clone_file_range,
                      ^
/opt/cifs_old/cifsfs.c:1129:22: note: (near initialization for ‘cifs_file_nobrl_ops.mmap’)
/opt/cifs_old/cifsfs.c:1145:2: error: unknown field ‘copy_file_range’ specified in initializer
  .copy_file_range = cifs_copy_file_range,
  ^
/opt/cifs_old/cifsfs.c:1145:21: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .copy_file_range = cifs_copy_file_range,
                     ^
/opt/cifs_old/cifsfs.c:1145:21: note: (near initialization for ‘cifs_file_strict_nobrl_ops.compat_ioctl’)
/opt/cifs_old/cifsfs.c:1146:2: error: unknown field ‘clone_file_range’ specified in initializer
  .clone_file_range = cifs_clone_file_range,
  ^
/opt/cifs_old/cifsfs.c:1146:22: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .clone_file_range = cifs_clone_file_range,
                      ^
/opt/cifs_old/cifsfs.c:1146:22: note: (near initialization for ‘cifs_file_strict_nobrl_ops.mmap’)
/opt/cifs_old/cifsfs.c:1162:2: error: unknown field ‘copy_file_range’ specified in initializer
  .copy_file_range = cifs_copy_file_range,
  ^
/opt/cifs_old/cifsfs.c:1162:21: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .copy_file_range = cifs_copy_file_range,
                     ^
/opt/cifs_old/cifsfs.c:1162:21: note: (near initialization for ‘cifs_file_direct_nobrl_ops.compat_ioctl’)
/opt/cifs_old/cifsfs.c:1163:2: error: unknown field ‘clone_file_range’ specified in initializer
  .clone_file_range = cifs_clone_file_range,
  ^
/opt/cifs_old/cifsfs.c:1163:22: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .clone_file_range = cifs_clone_file_range,
                      ^
/opt/cifs_old/cifsfs.c:1163:22: note: (near initialization for ‘cifs_file_direct_nobrl_ops.mmap’)
/opt/cifs_old/cifsfs.c:1170:2: error: unknown field ‘iterate_shared’ specified in initializer
  .iterate_shared = cifs_readdir,
  ^
/opt/cifs_old/cifsfs.c:1170:20: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .iterate_shared = cifs_readdir,
                    ^
/opt/cifs_old/cifsfs.c:1170:20: note: (near initialization for ‘cifs_dir_ops.owner’)
/opt/cifs_old/cifsfs.c:1174:2: error: unknown field ‘copy_file_range’ specified in initializer
  .copy_file_range = cifs_copy_file_range,
  ^
/opt/cifs_old/cifsfs.c:1174:21: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .copy_file_range = cifs_copy_file_range,
                     ^
/opt/cifs_old/cifsfs.c:1174:21: note: (near initialization for ‘cifs_dir_ops.compat_ioctl’)
/opt/cifs_old/cifsfs.c:1175:2: error: unknown field ‘clone_file_range’ specified in initializer
  .clone_file_range = cifs_clone_file_range,
  ^
/opt/cifs_old/cifsfs.c:1175:22: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .clone_file_range = cifs_clone_file_range,
                      ^
/opt/cifs_old/cifsfs.c:1175:22: note: (near initialization for ‘cifs_dir_ops.mmap’)
/opt/cifs_old/cifsfs.c: In function ‘cifs_init_inodecache’:
/opt/cifs_old/cifsfs.c:1194:23: error: ‘SLAB_ACCOUNT’ undeclared (first use in this function)
       SLAB_MEM_SPREAD|SLAB_ACCOUNT),
                       ^
/opt/cifs_old/cifsfs.c:1194:23: note: each undeclared identifier is reported only once for each function it appears in
cc1: some warnings being treated as errors
scripts/Makefile.build:277: recipe for target '/opt/cifs_old/cifsfs.o' failed
make[2]: *** [/opt/cifs_old/cifsfs.o] Error 1
Makefile:1439: recipe for target '_module_/opt/cifs_old' failed
make[1]: *** [_module_/opt/cifs_old] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-141-generic'
Makefile:14: recipe for target 'all' failed
make: *** [all] Error 2
cp: cannot stat 'cifs_old.ko': No such file or directory

```

**Comment by RobertCsordas** [comment]
You need this only starting from 4.13. Prior kernels should work just fine. Please see the "Removing" section in the readme.
